Repository iina/iina, pull requests merged in 2018-05, with the labels that each got.

#1696 Enhancement on playlist and features related to watch_later
  iina.xcodeproj/project.pbxproj
  iina/AppDelegate.swift
  iina/Assets.xcassets/history.imageset/Contents.json
  iina/Assets.xcassets/history.imageset/history.pdf
  iina/Base.lproj/InitialWindowController.xib
  iina/Base.lproj/PlaylistViewController.xib
  iina/Extensions.swift
  iina/FFmpegController.h
  iina/FFmpegController.m
  iina/Info.plist
  iina/InitialWindowController.swift
  iina/MPVController.swift
  iina/PlaybackHistory.swift
  iina/PlaybackInfo.swift
  iina/PlayerCore.swift
  iina/PlaylistPlaybackProgressView.swift
  iina/PlaylistViewController.swift
  iina/Preference.swift
  iina/Utility.swift
Labels: progress: pr ready

#1678 Search subtitles online automatically (#639)
  iina/AutoFileMatcher.swift
  iina/PlayerCore.swift
  iina/Preference.swift
Labels: progress: wip

#1731 Put the mute button in the mini player into slider popup, fix #1664
  iina/MiniPlayerWindowController.swift
  iina/MiniPlayerWindowController.xib
  iina/PlayerCore.swift
Labels: feature: music mode, feature: ui/ux
