Repository iina/iina, pull requests merged in 2018-07, with the labels that each got.

#1838 Respect theme settings in additionalInfoView
  iina/MainWindowController.swift
Labels: feature: ui/ux

#1497 Fix counting of string types in check_translation.
  other/check_translation.swift
Labels: type: localization

#1844 french localisation for 1.0.0 beta3
  iina.xcodeproj/project.pbxproj
  iina/fr.lproj/FontPickerWindowController.strings
  iina/fr.lproj/InitialWindowController.strings
  iina/fr.lproj/Localizable.strings
  iina/fr.lproj/MainMenu.strings
  iina/fr.lproj/PlaylistViewController.strings
  iina/fr.lproj/PrefAdvancedViewController.strings
  iina/fr.lproj/PrefCodecViewController.strings
  iina/fr.lproj/PrefControlViewController.strings
  iina/fr.lproj/PrefGeneralViewController.strings
  iina/fr.lproj/PrefKeyBindingViewController.strings
  iina/fr.lproj/PrefOSCToolbarSettingsSheetController.strings
  iina/fr.lproj/PrefSubViewController.strings
  iina/fr.lproj/PrefUIViewController.strings
  iina/fr.lproj/PrefUtilsViewController.strings
  iina/fr.lproj/PreferenceWindowController.strings
  iina/fr.lproj/SubChooseViewController.strings
Labels: type: localization

#1608 [MainWindowController] Refactor fullscreen logic
  iina/MPVController.swift
  iina/MainWindowController.swift
  iina/MainWindowMenuActions.swift
  iina/MenuController.swift
  iina/PlayerCore.swift
Labels: type: refactor
