Repository iina/iina, pull requests merged in 2022-11, with the labels that each got.

#3469 Fix screenshot crash with long video title, #3334
  iina/Base.lproj/Localizable.strings
  iina/Extensions.swift
  iina/MPVController.swift
  iina/Utility.swift
  iina/en.lproj/Localizable.strings
Labels: bug: crash, type: localization

#4041 Migrate build settings to xcconfigs
  Configs/Debug.xcconfig
  Configs/Deployment.xcconfig
  Configs/OpenInIINA.xcconfig
  Configs/Release.xcconfig
  Configs/Shared.xcconfig
  Configs/iina-cli.xcconfig
  Configs/iina.xcconfig
  OpenInIINA/Info.plist
  iina.xcodeproj/project.pbxproj
Labels: type: project management

#4028 Fix PluginOverlayView clickable.
  iina/PluginOverlayView.swift
Labels: feature: plugin

#4047 Update Sparkle to 2.3.0
  iina.xcodeproj/project.pbxproj
  iina/AppDelegate.swift
  iina/Base.lproj/MainMenu.xib
  iina/Base.lproj/PrefGeneralViewController.xib
  iina/PrefGeneralViewController.swift
Labels: other: upstream

#4048 Ignore warnings from FFmpeg' and mpv's header files
  iina/FFmpegController.m
  iina/iina-Bridging-Header.h
Labels: type: project management
