Repository iina/iina, pull requests merged in 2024-05, with the labels that each got.

#4736 Display thumbnails in DAR instead of SAR
  iina/MainWindowController.swift
  iina/MiniPlayerWindowController.swift
  iina/PlayerCore.swift
  iina/ThumbnailPeekView.swift
Labels: bug, feature: window

#4798 Refactor how AppDelegate is accessed
  iina/AppDelegate.swift
  iina/FilterWindowController.swift
  iina/InitialWindowController.swift
  iina/JavascriptAPIMenu.swift
  iina/Logger.swift
  iina/MainMenuActions.swift
  iina/PlayerCore.swift
  iina/PlayerWindowController.swift
  iina/PrefAdvancedViewController.swift
  iina/PrefGeneralViewController.swift
  iina/PrefUtilsViewController.swift
  iina/Utility.swift
Labels: type: refactor

#4953 Fix text clipping when textfields have multiple lines in inspector
  iina/Base.lproj/InspectorWindowController.xib
Labels: feature: ui/ux

#4958 More RTL related fixes on OSC
  iina/Assets.xcassets/Icons/backward.imageset/Contents.json
  iina/Assets.xcassets/Icons/forward.imageset/Contents.json
  iina/Base.lproj/MainWindowController.xib
  iina/Base.lproj/PrefUtilsViewController.xib
  iina/MainWindowController.swift
  iina/TimeLabelOverflowedStackView.swift
Labels: feature: ui/ux, type: localization

#4264 Migrate color prefs away from NSArchiver
  iina.xcodeproj/project.pbxproj
  iina/AppDelegate.swift
  iina/Base.lproj/PrefSubViewController.xib
  iina/Extensions.swift
  iina/LegacyMigration.swift
  iina/MPVController.swift
  iina/PrefSubViewController.swift
  iina/Preference.swift
Labels: priority: high
